# Generated by Django 3.1.7 on 2021-03-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210320_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_data',
            field=models.JSONField(),
        ),
    ]
