# Generated by Django 3.1.7 on 2021-03-20 18:39

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210321_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_data',
            field=models.JSONField(default=register.models.my_default),
        ),
    ]
